flyway.url=jdbc:postgresql://ep-spring-dawn-ayhwgk7a-pooler.c-5.us-east-2.aws.neon.tech/neondb?sslmode=require
flyway.user=neondb_owner
flyway.password=npg_iRk2atlBzjq5
flyway.locations=filesystem:src/main/resources/db/migration
